#define COMSIG_AI_PATH_GENERATED "ai_path_generated"
#define COMSIG_AI_MOVEMENT_SET "ai_movement_set"
#define COMSIG_AI_GENERAL_CHANGE "ai_general_change"
#define COMSIG_AI_FUTURE_PATH_GENERATED "ai_future_path_generated"
#define COMSIG_AI_PATH_SWAPPED "ai_path_swapped"
